
* Is the working class license an open source license?

The Open Source Definition implements "5. No discrimination against
persons or groups".

So, a possitive discrimination in a socialdemocracy sense is out of
Open Source Definition. To help to people with few resources, females,
or some minority, we must use another kind of licenses or other ideas.

You can visit [[https://opensource.org/osd][Open Source Definition]] to read the full definition.

* Is the working class license a propietary software license? 

[[https://www.gnu.org/proprietary/proprietary.html][Propietary software]] is a term used by GNU about not Free Software, the
working class license is non Free Software in the GNU sense. 

We want claim that the positive discrimination in the software
licenses is a good point for the freedom by the people. We are helping
to United Nations to reach the objective about [[https://www.un.org/sustainabledevelopment/inequality/][Inequality]].

* Is it possible make this license compatible with GPL?
This license is not compatible with GPL. But if you are the copyright
holder, you can consider create a dual license for your
software. Perhaps you want make the most new releases for the working
class and give GPL software with other versions.
* Is it so hard write an operating system with this license?
If you are interested in this task I suggest starts from a BSD
operating system. BSD license allows change the license, so you could
identify a lot of software to use in your new operating system
